// ─────────────────────────────────────────────────────────────────────────────
// audit-log.ts — Append-only Markdown audit trail
//
// Format: Markdown table in _System/Sync_Log.md.
// Context is serialized as a code-fenced JSON block after the table row so
// that the table stays readable while full diagnostic data is preserved.
// ─────────────────────────────────────────────────────────────────────────────

import { Vault, normalizePath } from "obsidian";
import { SyncEvent, SyncEventType, SyncStatus, GitSyncSettings } from "./types";

const TABLE_HEADER = `# Git Sync — Audit Log

> Auto-generated by the Vault Git Sync plugin. Do not edit manually.
> Each row may be followed by a detail block with full diagnostic context.

| Timestamp | Event | Status | Message |
|---|---|---|---|\n`;

export class AuditLog {
  constructor(private vault: Vault) {}

  async append(event: SyncEvent, settings: GitSyncSettings): Promise<void> {
    if (!settings.auditLogEnabled) return;

    const logPath = normalizePath(settings.auditLogPath);
    const dir = logPath.split("/").slice(0, -1).join("/");
    if (dir && !(await this.vault.adapter.exists(dir))) {
      await this.vault.adapter.mkdir(dir);
    }

    const entry = this.serialize(event);
    const exists = await this.vault.adapter.exists(logPath);
    if (!exists) {
      await this.vault.adapter.write(logPath, TABLE_HEADER + entry);
    } else {
      const current = await this.vault.adapter.read(logPath);
      await this.vault.adapter.write(logPath, current + entry);
    }
  }

  private serialize(e: SyncEvent): string {
    const safeMsg = e.message.replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 200);
    const row = `| \`${e.timestamp}\` | **${e.type}** | ${e.status} | ${safeMsg} |\n`;

    if (!e.context) return row;

    // Pretty-print context as a collapsed detail block
    const ctx = JSON.stringify(e.context, null, 2);
    const detail = `\n<details><summary>context</summary>\n\n\`\`\`json\n${ctx}\n\`\`\`\n\n</details>\n\n`;
    return row + detail;
  }

  /** Factory — builds a fully populated SyncEvent */
  static event(
    type: SyncEventType,
    status: SyncStatus,
    message: string,
    context?: SyncEvent["context"]
  ): SyncEvent {
    return { timestamp: new Date().toISOString(), type, status, message, context };
  }

  /** Extract structured context from any thrown value */
  static errorContext(e: unknown, extra: Record<string, unknown> = {}): SyncEvent["context"] {
    const err = e as { name?: string; data?: unknown; stack?: string };
    return {
      errorName:  err?.name    ?? "Error",
      errorData:  err?.data    ? JSON.stringify(err.data) : undefined,
      errorStack: err?.stack   ? err.stack.split("\n").slice(0, 6).join(" | ") : undefined,
      ...extra,
    };
  }
}
